/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.List;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Multa;
import modelo.MySQL;
import modelo.Proprietarios;
import modelo.Veiculos;

/**
 *
 * @author Rodrigo Vanhoz
 */
public class MulCad extends javax.swing.JDialog {

    /**
     * Creates new form MulCad
     */
    private MySQL sql = new MySQL("MULTA");
    private javax.swing.JFrame pFrame;
    private JDialog pDialog;
    private Proprietarios prop = new Proprietarios();
    private Veiculos vei = new Veiculos();
    private Multa mul = new Multa();
    
    public MulCad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        pFrame = (JFrame)parent;
        pegaTipoMulta();
    }
    public MulCad(javax.swing.JFrame parentFrame, MySQL SQL) {
        
        initComponents();

        this.pFrame = parentFrame;
        this.sql      = SQL;
        
        pegaTipoMulta();
    }

    public MulCad(javax.swing.JDialog parentDialog, MySQL SQL) {
        initComponents();

        this.pDialog = parentDialog;
        this.sql = SQL;
        
        pegaTipoMulta();
        
    }
    
    private void pegaTipoMulta() {
        jcGrauInfracao.removeAllItems();
        
        for ( int i=0; i < mul.getTamanho(); i ++ ) {
            jcGrauInfracao.addItem(mul.getNomeValor(i));
        }
    }
    
    private void propInlcui( ) {
        if ( prop.getCodigo() != -1 ) {
            jtNomeProp.setText(prop.getNome());
        }
        if ( vei.getCodigo() != -1 ) {
            jtNomeVeiculo.setText(vei.getDescr());        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtNomeProp = new javax.swing.JTextField();
        jtNomeVeiculo = new javax.swing.JTextField();
        jtData = new javax.swing.JFormattedTextField();
        jcGrauInfracao = new javax.swing.JComboBox();
        jtPontuacao = new javax.swing.JTextField();
        jbOk = new javax.swing.JButton();
        jbCancela = new javax.swing.JButton();
        jbTabelaProp = new javax.swing.JButton();
        jbTabelaVei = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setText("Proprietário");

        jLabel2.setText("Veículo");

        jLabel3.setText("Data");

        jLabel4.setText("Pontuação");

        jLabel5.setText("Grau da Infração");

        jtNomeProp.setEditable(false);

        jtNomeVeiculo.setEditable(false);

        jtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/mm/yyyy"))));
        jtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDataActionPerformed(evt);
            }
        });

        jcGrauInfracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbOk.setText("Ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbCancela.setText("Cancela");
        jbCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelaActionPerformed(evt);
            }
        });

        jbTabelaProp.setText("...");
        jbTabelaProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTabelaPropActionPerformed(evt);
            }
        });

        jbTabelaVei.setText("...");
        jbTabelaVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTabelaVeiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtNomeProp)
                    .addComponent(jtNomeVeiculo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbOk)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbCancela))
                        .addComponent(jcGrauInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbTabelaProp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTabelaVei, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNomeProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTabelaProp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNomeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTabelaVei))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcGrauInfracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jbCancela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDataActionPerformed

    private void jbCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelaActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        try {
            sql.abrebanco();
            String sqlLinha = "Insert INTO Multa (codpro,codvei,data,pontuacao,tipo)"
                            + "VALUES (?,?,?,?,?)";
            
            PreparedStatement stmt = sql.connection.prepareStatement(sqlLinha);
            
            stmt.setInt   ( 1, prop.getCodigo());
            stmt.setInt   ( 2, vei.getCodigo());
            try {
                stmt.setDate  ( 3,new java.sql.Date(new SimpleDateFormat("dd/mm/yyyy").parse(jtData.getText()).getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(MulCad.class.getName()).log(Level.SEVERE, null, ex);
            }
            stmt.setInt   ( 4, Integer.parseInt(jtPontuacao.getText()));
            stmt.setInt   ( 5, jcGrauInfracao.getSelectedIndex()+1);
            
            int result = stmt.executeUpdate();
            if ( result != 1 ) {
                JOptionPane.showMessageDialog(null, "ERRO: Multa não cadastrada");
            }
        } catch ( SQLException e ) {
            e.printStackTrace();
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbTabelaPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTabelaPropActionPerformed
        this.setVisible(false);
        
        ProNaveg pn = new ProNaveg(this, prop);
        pFrame.getContentPane().add(pn);
        pFrame.repaint();
        
        pn.moveToFront();
        jtNomeProp.requestFocus();
    }//GEN-LAST:event_jbTabelaPropActionPerformed

    private void jbTabelaVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTabelaVeiActionPerformed
        this.setVisible(false);
        
        VeiNaveg vn = new VeiNaveg(vei, this);
        pFrame.getContentPane().add(vn);
        pFrame.repaint();
        
        vn.moveToFront();
        jtNomeVeiculo.requestFocus();
    }//GEN-LAST:event_jbTabelaVeiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        propInlcui();
    }//GEN-LAST:event_formWindowActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.setVisible(true);
    }//GEN-LAST:event_formFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MulCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MulCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MulCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MulCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MulCad dialog = new MulCad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCancela;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbTabelaProp;
    private javax.swing.JButton jbTabelaVei;
    private javax.swing.JComboBox jcGrauInfracao;
    private javax.swing.JFormattedTextField jtData;
    private javax.swing.JTextField jtNomeProp;
    private javax.swing.JTextField jtNomeVeiculo;
    private javax.swing.JTextField jtPontuacao;
    // End of variables declaration//GEN-END:variables
}
